FROM node:18

# Install FFmpeg
RUN apt-get update && \
    apt-get install -y ffmpeg && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./

RUN npm install -g nodemon typescript ts-node
RUN npm install

EXPOSE 9229

CMD ["npm", "run", "dev:debug"] 