name: Deploy to Production

on:
  push:
    branches:
      - main  # or master, depending on your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push client
        uses: docker/build-push-action@v4
        with:
          context: ./client
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mp4-to-gif-client:latest

      - name: Build and push server
        uses: docker/build-push-action@v4
        with:
          context: ./server
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mp4-to-gif-server:latest

      - name: Build and push worker
        uses: docker/build-push-action@v4
        with:
          context: ./worker
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mp4-to-gif-worker:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /opt/mp4-to-gif
            docker stack rm mp4-to-gif || true
            sleep 10
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/mp4-to-gif-client:latest
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/mp4-to-gif-server:latest
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/mp4-to-gif-worker:latest
            docker stack deploy -c docker/docker-compose.prod.yml mp4-to-gif 